import { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  schema: './src/common/lib/graphql/schema.graphql',
  // this assumes that all your source files are in a top-level `src/` directory - you might need to adjust this to your file structure
  documents: ['src/**/*.{ts,tsx}'],
  generates: {
    './src/common/lib/graphql/__generated__/': {
      preset: 'client',
      plugins: [
        {
          add: {
            content:
              '// This file is automatically generated by GraphQL Codegen. Do not edit.',
          },
        },
      ],
      presetConfig: {
        gqlTagName: 'gql',
      },
    },
  },
  ignoreNoDocuments: true,
}

export default config
