query Bills($where: Bill_where, $limit: Int, $page: Int, $sort: String) {
  Bills(where: $where, limit: $limit, page: $page, sort: $sort) {
    hasNextPage
    hasPrevPage
    limit
    nextPage
    offset
    page
    pagingCounter
    prevPage
    totalDocs
    totalPages
    docs {
      id
      i18n {
        en {
          title
          summary
          actionsOverview
          actionsAll
        }
        zh {
          title
          summary
          actionsOverview
          actionsAll
        }
      }
      congress
      number
      type
      introducedAt {
        datetime
        precision
      }
      isFeatured
      categories {
        id
        i18n {
          en {
            name
          }
          zh {
            name
          }
        }
      }
      tags {
        id
        i18n {
          en {
            name
          }
          zh {
            name
          }
        }
        isFeatured
      }
      statusTracker {
        currentStep
        passedSteps
        futureSteps
      }
      sponsor {
        people {
          id
          i18n {
            en {
              firstName
              lastName
              middleName
              displayName
              bio
              otherNames {
                otherName
                id
              }
            }
            zh {
              firstName
              lastName
              middleName
              displayName
              bio
              otherNames {
                otherName
                id
              }
            }
          }
          photo {
            id
            alt
            url
            filename
            mimeType
            width
            height
          }
          birthday {
            datetime
            precision
          }
          gender
          tags {
            id
            i18n {
              en {
                name
              }
              zh {
                name
              }
            }
            isFeatured
          }
          congressionalData {
            bioGuideId
            govTrackId
            committees {
              systemCode
              name
              title
              subcommittees {
                systemCode
                name
                title
                id
              }
              id
            }
          }
          experiences {
            company
            category
            isCurrent
            positions {
              title
              description
              start {
                datetime
                precision
              }
              end {
                datetime
                precision
              }
              state
              district
              party
              congresses
              officialAreas
              companyType
              id
            }
            id
          }
          publications {
            title
            abstract
            link
            id
          }
          links {
            type
            title
            link
            id
          }
          partyChangeRecords {
            newParty
            oldParty
            changedAt {
              datetime
              precision
            }
            id
          }
          viewCount
          billCount
          currentParty
          records {
            id
            title
            description
            status
            sources {
              link
              id
            }
          }
          sponsorBills {
            id
            title
            congress
            number
            type
            isFeatured
          }
          cosponsorBills {
            id
            title
            congress
            number
            type
            isFeatured
          }
          votes {
            vote {
              id
              rollCall
              congress
              session
            }
            stance
            party
            id
          }
          displayName
          bio
          govTrackId
        }
        party
      }
      cosponsors {
        people {
          id
          i18n {
            en {
              firstName
              lastName
              middleName
              displayName
              bio
              otherNames {
                otherName
                id
              }
            }
            zh {
              firstName
              lastName
              middleName
              displayName
              bio
              otherNames {
                otherName
                id
              }
            }
          }
          photo {
            id
            alt
            url
            filename
            mimeType
            width
            height
          }
          birthday {
            datetime
            precision
          }
          gender
          tags {
            id
            i18n {
              en {
                name
              }
              zh {
                name
              }
            }
            isFeatured
          }
          congressionalData {
            bioGuideId
            govTrackId
            committees {
              systemCode
              name
              title
              subcommittees {
                systemCode
                name
                title
                id
              }
              id
            }
          }
          experiences {
            company
            category
            isCurrent
            positions {
              title
              description
              start {
                datetime
                precision
              }
              end {
                datetime
                precision
              }
              state
              district
              party
              congresses
              officialAreas
              companyType
              id
            }
            id
          }
          publications {
            title
            abstract
            link
            id
          }
          links {
            type
            title
            link
            id
          }
          partyChangeRecords {
            newParty
            oldParty
            changedAt {
              datetime
              precision
            }
            id
          }
          viewCount
          billCount
          currentParty
          records {
            id
            title
            description
            status
            sources {
              link
              id
            }
          }
          sponsorBills {
            id
            title
            congress
            number
            type
            isFeatured
          }
          cosponsorBills {
            id
            title
            congress
            number
            type
            isFeatured
          }
          votes {
            vote {
              id
              rollCall
              congress
              session
            }
            stance
            party
            id
          }
          displayName
          bio
          govTrackId
        }
        constituency
        party
        cosponsoredAt {
          datetime
          precision
        }
        id
      }
      congressGovUrl
      popularityRank
      relatedBills {
        id
        i18n {
          en {
            title
            summary
            actionsOverview
            actionsAll
          }
          zh {
            title
            summary
            actionsOverview
            actionsAll
          }
        }
        congress
        number
        type
        introducedAt {
          datetime
          precision
        }
        isFeatured
        categories {
          id
          i18n {
            en {
              name
            }
            zh {
              name
            }
          }
        }
        tags {
          id
          i18n {
            en {
              name
            }
            zh {
              name
            }
          }
          isFeatured
        }
        statusTracker {
          currentStep
          passedSteps
          futureSteps
        }
        sponsor {
          people {
            id
            i18n {
              en {
                firstName
                lastName
                middleName
                displayName
                bio
                otherNames {
                  otherName
                  id
                }
              }
              zh {
                firstName
                lastName
                middleName
                displayName
                bio
                otherNames {
                  otherName
                  id
                }
              }
            }
            photo {
              id
              alt
              url
              filename
              mimeType
              width
              height
            }
            birthday {
              datetime
              precision
            }
            gender
            tags {
              id
              i18n {
                en {
                  name
                }
                zh {
                  name
                }
              }
              isFeatured
            }
            congressionalData {
              bioGuideId
              govTrackId
              committees {
                systemCode
                name
                title
                subcommittees {
                  systemCode
                  name
                  title
                  id
                }
                id
              }
            }
            experiences {
              company
              category
              isCurrent
              positions {
                title
                description
                start {
                  datetime
                  precision
                }
                end {
                  datetime
                  precision
                }
                state
                district
                party
                congresses
                officialAreas
                companyType
                id
              }
              id
            }
            publications {
              title
              abstract
              link
              id
            }
            links {
              type
              title
              link
              id
            }
            partyChangeRecords {
              newParty
              oldParty
              changedAt {
                datetime
                precision
              }
              id
            }
            viewCount
            billCount
            currentParty
            records {
              id
              title
              description
              status
              sources {
                link
                id
              }
            }
            sponsorBills {
              id
              title
              congress
              number
              type
              isFeatured
            }
            cosponsorBills {
              id
              title
              congress
              number
              type
              isFeatured
            }
            votes {
              vote {
                id
                rollCall
                congress
                session
              }
              stance
              party
              id
            }
            displayName
            bio
            govTrackId
          }
          party
        }
      }
      title
      summary
      latestActionTime
      updatedAt
      createdAt
    }
  }
}
