export const config = {
  NODE_ENV: process.env.NODE_ENV,
  SOUNDON_API_TOKEN: process.env.NEXT_PUBLIC_SOUNDON_API_TOKEN,
  SOUNDON_PODCAST_ID: process.env.NEXT_PUBLIC_SOUNDON_PODCAST_ID,
  GRAPHQL_API_URL: process.env.NEXT_PUBLIC_GRAPHQL_API_URL,
} as const
