export const config = {
  NODE_ENV: process.env.NODE_ENV,
  WEB_BASE_URL: process.env.NEXT_PUBLIC_WEB_BASE_URL,
  SOUNDON_API_TOKEN: process.env.NEXT_PUBLIC_SOUNDON_API_TOKEN,
  SOUNDON_PODCAST_ID: process.env.NEXT_PUBLIC_SOUNDON_PODCAST_ID,
  GRAPHQL_API_URL: process.env.NEXT_PUBLIC_GRAPHQL_API_URL,
  AUTH0_DOMAIN: process.env.NEXT_PUBLIC_AUTH0_DOMAIN!,
  AUTH0_CLIENT_ID: process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID!,
  AUTH0_REDIRECT_URI: process.env.NEXT_PUBLIC_AUTH0_REDIRECT_URI!,
} as const
