name: "[dev] Build and Deploy to Azure"

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/r-cicd.yml
    with:
      environment: Development
