// List all parties in United States
export enum Party {
  DEMOCRAT = 'DEMOCRAT',
  REPUBLICAN = 'REPUBLICAN',
  INDEPENDENT = 'INDEPENDENT',
  LIBERTARIAN = 'LIBERTARIAN',
  GREEN = 'GREEN',
  CONSTITUTION = 'CONSTITUTION',
  OTHER = 'OTHER',
}
